apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: backend
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: main
        image: docker.io/vianagallery/gallery-api
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: TEST_NAME
          value: Cluster Prod
        - name: API_VERSION
          value: 1.0.0
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: POSTGRES_URL
        - name: ADMIN_JWT
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: ADMIN_JWT
        # CloudFlareImages Account Id
        - name: CFI_ID
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: CFI_ID
        - name: CFI_TOKEN
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: CFI_TOKEN
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-hub-cred

###### Service ######
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: backend
  labels:
    app: api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    # protocol: TCP
  selector:
    app: api
    # internalTrafficPolicy: Cluster
    # ipFamilies:
    # - IPv4
    # ipFamilyPolicy: SingleStack
    # sessionAffinity: None
    # type: LoadBalancer
# status:
#   loadBalancer: {}

###### Ingress ######
# ---
# ## If using with nginx ingress controller
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-ingress
#   namespace: backend
#   annotations:
#     # cert-manager.io/issuer: letsencrypt-nginx
#     # acme.cert-manager.io/http01-edit-in-place: "true"
    
#     # cert-manager.io/issue-temporary-certificate: "true"
# spec:
#   ingressClassName: nginx
#   # tls:
#   # - hosts:
#   #   - api.dreampuppy.com.br
#   #   secretName: gallery-tls-secret
#   rules:
#   - host: api.dreampuppy.com.br
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: api
#             port:
#               number: 80

---
## If using with Ambassador Edge Stack and CRDs