apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  # type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    # protocol: TCP
  selector:
    app: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: main
        image: wordpress
        # command: ["echo"]
        # args: ["ola"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
            cpu: "0.4"
          requests:
            memory: 64Mi
            cpu: "0.1"
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql.blog.svc.cluster.local
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: DB_USER
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: DB_NAME
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: DB_PASSWORD
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      imagePullSecrets:
      - name: docker-hub-cred
---