apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: frontend
  labels:
    app: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www-container
        image: vianagallery/frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: "0.3"
          requests:
            memory: 64Mi
            cpu: "0.1"
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: docker-hub-cred
---
apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: www
  labels:
    app: www
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
    # protocol: TCP
  selector:
    app: www
    # internalTrafficPolicy: Cluster
    # ipFamilies:
    # - IPv4
    # ipFamilyPolicy: SingleStack
    # sessionAffinity: None
    # type: LoadBalancer
# status:
#   loadBalancer: {}
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: www-ingress
#   namespace: frontend
#   annotations: 
#       cert-manager.io/issuer: letsencrypt-nginx
#       # acme.cert-manager.io/http01-edit-in-place: "true" 
# spec:
#   ingressClassName: nginx
#   tls:
#   - hosts:
#     - www.dreampuppy.com.br
#     secretName: www-tls-secret
#   rules:
#   - host: www.dreampuppy.com.br
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: www
#             port:
#               number: 80
